[workspace]
members = ["logan-bench",
    "logan-bin",
    "logan-client",
    "logan-common",
    "logan-protocol",
    "logan-server",
    "logan-storage", "logan-tpc",
]
resolver = "2"

[workspace.package]
version = "0.1.0"
edition = "2024"
