[package]
name = "logan-tpc"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.100"
bytes = "1.11.0"
futures = "0.3.31"
glommio = "0.9.0"
logan-protocol = { version = "0.1.0", path = "../logan-protocol" }
num_cpus = "1.17.0"
