[package]
name = "logan-storage"
version.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.100"
crc32fast = "1.5.0"
dashmap = "6.1.0"
tracing = "0.1.43"
logan-protocol = { path = "../logan-protocol" }
bytes = "1.9.0"

[dev-dependencies]
proptest = "1.9.0"
tempfile = "3.23.0"
